// Copyright 2026 Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

use serde::{Deserialize, Serialize};

/// Desired runtime state for agent-assisted execution.
#[derive(Clone, Debug, PartialEq, Eq, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub struct AgentRuntimeConfig {
    /// Target runtime state.
    pub state: AgentRuntimeState,
    /// Optional pause behavior when entering `LlmWaiting`.
    #[serde(default)]
    pub pause_on_wait: Option<bool>,
    /// Deprecated and ignored. Kept for backward compatibility.
    #[serde(default)]
    pub target_balloon_mib: Option<u32>,
    /// Deprecated and ignored. Kept for backward compatibility.
    #[serde(default)]
    pub acknowledge_on_stop: Option<bool>,
}

/// Valid runtime states for agent-assisted execution.
#[derive(Clone, Debug, PartialEq, Eq, Deserialize, Serialize)]
pub enum AgentRuntimeState {
    /// Runtime waits for external LLM/network processing.
    LlmWaiting,
    /// Runtime is actively running in the guest.
    Running,
}

/// Configuration used when transitioning into LLM wait mode.
#[derive(Clone, Debug, PartialEq, Eq, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub struct EnterLlmWaitConfig {
    /// Optional pause behavior while reclaiming memory.
    #[serde(default)]
    pub pause_on_wait: Option<bool>,
}

impl From<AgentRuntimeConfig> for EnterLlmWaitConfig {
    fn from(value: AgentRuntimeConfig) -> Self {
        Self {
            pause_on_wait: value.pause_on_wait,
        }
    }
}

/// Response payload forwarded by host-side orchestration back to the guest.
#[derive(Clone, Debug, PartialEq, Eq, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub struct SubmitLlmResponseConfig {
    /// Request identifier generated by the caller.
    pub request_id: String,
    /// Guest vsock listening port that consumes responses.
    pub vsock_port: u32,
    /// Response payload to deliver to the guest.
    pub response: String,
    /// Whether to automatically leave `LlmWaiting` before forwarding the response.
    #[serde(default)]
    pub resume_vm: Option<bool>,
}
